import '../assets/styles/layers.css';
import 'vuetify/styles';
import { createVuetify } from 'vuetify';
import { zhHans } from 'vuetify/locale';
import { aliases, md } from 'vuetify/iconsets/md';
import { md3 } from 'vuetify/blueprints';

const vuetify = createVuetify({
  locale: {
    locale: 'zhHans',
    messages: { zhHans },
  },
  icons: {
    defaultSet: 'md',
    aliases,
    sets: {
      md,
    },
  },
  display: {
    mobileBreakpoint: 'md',
    thresholds: {
      xs: 0, sm: 600, md: 960, lg: 1280, xl: 1920, xxl: 2560,
    },
  },
  theme: {
    defaultTheme: 'light',
    themes: {
      light: {
        colors: {
          primary: '#00649c',
          'primary-dim': '#005789',
          'on-primary': '#f6f9ff',
          'primary-container': '#8ac6ff',
          'on-primary-container': '#004066',
          'inverse-primary': '#70bcff',
          'primary-fixed': '#8ac6ff',
          'primary-fixed-dim': '#6db9fc',
          'on-primary-fixed': '#002a46',
          'on-primary-fixed-variant': '#004974',
          secondary: '#7a546a',
          'secondary-dim': '#6c485e',
          'on-secondary': '#fff7f8',
          'secondary-container': '#ffd8ec',
          'on-secondary-container': '#6b465d',
          'secondary-fixed': '#ffd8ec',
          'secondary-fixed-dim': '#f7c7e2',
          'on-secondary-fixed': '#57344a',
          'on-secondary-fixed-variant': '#765067',
          tertiary: '#944271',
          'tertiary-dim': '#863665',
          'on-tertiary': '#fff7f8',
          'tertiary-container': '#fd9ace',
          'on-tertiary-container': '#631847',
          'tertiary-fixed': '#fd9ace',
          'tertiary-fixed-dim': '#ed8cc0',
          'on-tertiary-fixed': '#45002f',
          'on-tertiary-fixed-variant': '#6e2250',
          error: '#ac3434',
          'error-dim': '#70030f',
          'on-error': '#fff7f6',
          'error-container': '#f56965',
          'on-error-container': '#65000b',
          'surface-dim': '#c6dbff',
          surface: '#f8f9ff',
          'surface-bright': '#f8f9ff',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#eff3ff',
          'surface-container': '#e6eeff',
          'surface-container-high': '#dde9ff',
          'surface-container-highest': '#d4e3ff',
          'on-surface': '#183355',
          'on-surface-variant': '#476084',
          outline: '#637ca2',
          'outline-variant': '#9ab3dc',
          'inverse-surface': '#020f20',
          'inverse-on-surface': '#919eb4',
          'surface-variant': '#d4e3ff',
          'surface-tint': '#00649c',
          background: '#f8f9ff',
          'on-background': '#183355',
          shadow: '#000000',
          scrim: '#000000',
        },
        dark: false,
      },
      dark: {
        colors: {
          primary: '#b8dbff',
          'primary-dim': '#9ecefe',
          'on-primary': '#154e77',
          'primary-container': '#9ecefe',
          'on-primary-container': '#04456e',
          'inverse-primary': '#30638d',
          'primary-fixed': '#9ecefe',
          'primary-fixed-dim': '#90c0ef',
          'on-primary-fixed': '#003150',
          'on-primary-fixed-variant': '#164e77',
          secondary: '#debece',
          'secondary-dim': '#cfb0c0',
          'on-secondary': '#503947',
          'secondary-container': '#34202c',
          'on-secondary-container': '#b99cab',
          'secondary-fixed': '#fedced',
          'secondary-fixed-dim': '#efcedf',
          'on-secondary-fixed': '#513a48',
          'on-secondary-fixed-variant': '#6f5664',
          tertiary: '#ffafd7',
          'tertiary-dim': '#f794c8',
          'on-tertiary': '#6f2251',
          'tertiary-container': '#fd9ace',
          'on-tertiary-container': '#631847',
          'tertiary-fixed': '#fd9ace',
          'tertiary-fixed-dim': '#ed8cc0',
          'on-tertiary-fixed': '#45002f',
          'on-tertiary-fixed-variant': '#6e2250',
          error: '#ff716c',
          'error-dim': '#c94947',
          'on-error': '#490006',
          'error-container': '#8a1a1e',
          'on-error-container': '#ff9993',
          'surface-dim': '#060f1b',
          surface: '#060f1b',
          'surface-bright': '#182d48',
          'surface-container-lowest': '#000000',
          'surface-container-low': '#081423',
          'surface-container': '#0c1a2c',
          'surface-container-high': '#102035',
          'surface-container-highest': '#14263e',
          'on-surface': '#d9e6ff',
          'on-surface-variant': '#9aacca',
          outline: '#657692',
          'outline-variant': '#374962',
          'inverse-surface': '#f8f9ff',
          'inverse-on-surface': '#4d5564',
          'surface-variant': '#14263e',
          'surface-tint': '#b8dbff',
          background: '#060f1b',
          'on-background': '#d9e6ff',
          shadow: '#000000',
          scrim: '#000000',
        },
        dark: true,
      },
    },
  },
  defaults: {
    VBtn: {
      class: 'normal-case',
      rounded: 'pill',
    },
    VBtnGroup: {
      rounded: 'pill',
    },
    VSwitch: {
      color: 'primary',
      hideDetails: true,
      inset: true,
      trueIcon: 'check',
    },
    VCard: {
      color: 'surface-container',
    },
    global: {
      style: [{}],
    },
  },
  blueprint: md3,
});

export default vuetify;
