// eslint-disable-next-line import/extensions
import 'vuetify/styles';
import { createVuetify } from 'vuetify';
import { zhHans } from 'vuetify/locale';
import { aliases, md } from 'vuetify/iconsets/md';
import { md3 } from 'vuetify/blueprints';

const vuetify = createVuetify({
  locale: {
    locale: 'zhHans',
    messages: { zhHans },
  },
  icons: {
    defaultSet: 'md',
    aliases,
    sets: {
      md,
    },
  },
  theme: {
    defaultTheme: 'light',
    themes: {
      light: {
        colors: {
          background: '#ededf5',
          surface: '#faf8ff',
          'surface-dim': '#d9d9e1',
          'surface-bright': '#faf8ff',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#f3f3fb',
          'surface-container': '#ededf5',
          'surface-container-high': '#e8e7f0',
          'surface-container-highest': '#e2e2ea',
          'on-surface': '#1a1b21',
          'inverse-surface': '#2e3036',
          'inverse-on-surface': '#f0f0f8',
          outline: '#737783',
          'outline-variant': '#c3c6d4',
          primary: '#2b5bb5',
          'on-primary': '#ffffff',
          'primary-container': '#d9e2ff',
          'on-primary-container': '#001945',
          'inverse-primary': '#b0c6ff',
          secondary: '#475d91',
          'on-secondary': '#ffffff',
          'secondary-container': '#d9e2ff',
          'on-secondary-container': '#001946',
          tertiary: '#575e75',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#dbe2fd',
          'on-tertiary-container': '#141b2f',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#410002',
          'primary-fixed': '#d9e2ff',
          'primary-fixed-dim': '#b0c6ff',
          'on-primary-fixed': '#001945',
          'on-primary-fixed-variant': '#00429c',
          'secondary-fixed': '#d9e2ff',
          'secondary-fixed-dim': '#b1c6ff',
          'on-secondary-fixed': '#001946',
          'on-secondary-fixed-variant': '#2f4578',
          'tertiary-fixed': '#dbe2fd',
          'tertiary-fixed-dim': '#bfc6e0',
          'on-tertiary-fixed': '#141b2f',
          'on-tertiary-fixed-variant': '#3f465c',
          'surface-light': '#e8e7f0',
        },
        dark: false,
        variables: {
          'overlay-background': '#181b26',
        },
      },
      dark: {
        colors: {
          background: '#1e1f25',
          surface: '#111319',
          'surface-dim': '#111319',
          'surface-bright': '#37393f',
          'surface-container-lowest': '#0c0e14',
          'surface-container-low': '#1a1b21',
          'surface-container': '#1e1f25',
          'surface-container-high': '#282a30',
          'surface-container-highest': '#33353b',
          'on-surface': '#e2e2ea',
          'inverse-surface': '#e2e2ea',
          'inverse-on-surface': '#2e3036',
          outline: '#8d909d',
          'outline-variant': '#434652',
          primary: '#b0c6ff',
          'on-primary': '#002d6f',
          'primary-container': '#00429c',
          'on-primary-container': '#d9e2ff',
          'inverse-primary': '#2b5bb5',
          secondary: '#b1c6ff',
          'on-secondary': '#162e60',
          'secondary-container': '#2f4578',
          'on-secondary-container': '#d9e2ff',
          tertiary: '#bfc6e0',
          'on-tertiary': '#293044',
          'tertiary-container': '#3f465c',
          'on-tertiary-container': '#dbe2fd',
          error: '#ffb4ab',
          'on-error': '#690005',
          'error-container': '#93000a',
          'on-error-container': '#ffb4ab',
          'primary-fixed': '#d9e2ff',
          'primary-fixed-dim': '#b0c6ff',
          'on-primary-fixed': '#001945',
          'on-primary-fixed-variant': '#00429c',
          'secondary-fixed': '#d9e2ff',
          'secondary-fixed-dim': '#b1c6ff',
          'on-secondary-fixed': '#001946',
          'on-secondary-fixed-variant': '#2f4578',
          'tertiary-fixed': '#dbe2fd',
          'tertiary-fixed-dim': '#bfc6e0',
          'on-tertiary-fixed': '#141b2f',
          'on-tertiary-fixed-variant': '#3f465c',
          'surface-light': '#37393f',
        },
        dark: true,
        variables: {
          'overlay-background': '#181b26',
        },
      },
    },
  },
  defaults: {
    VBtn: {
      class: 'text-none',
    },
    global: {
      style: [{
        fontFamily: '"Roboto", "Noto Sans SC", "Microsoft YaHei", "微软雅黑", sans-serif',
      }],
    },
  },
  blueprint: md3,
});

export default vuetify;
