name: Node.js CI

on:
  push:
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies & build
        run: |
          pnpm i --frozen-lockfile
          pnpm build:app

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: packages/app/dist_electron/*.exe

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: "packages/app/dist_electron/*.exe"
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
